AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: API Gateway + Lambda to set branch protection on new GH repo


Parameters:
  Secret:
    Type: String
  GHToken:
    Type: String
  SubscriptionEmail:
    Type: String
    Default: riznob@gmail.com
    ConstraintDescription: must be an email address

Resources:
  processWebhookApi:
    Type: AWS::Serverless::Api
    Properties:
      Name: !Sub ${AWS::StackName}-processWebhookApi
      StageName: Prod
      Cors: "'*'"
  processWebhook:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Sub ${AWS::StackName}-processWebhook
      Description: processWebhook endpoint
      CodeUri: src/
      Handler: processWebhook/index.handler
      Runtime: nodejs14.x
      MemorySize: 256
      Timeout: 120
      Events:
        Root:
          Type: Api
          Properties:
            RestApiId: !Ref processWebhookApi
            Path: /processWebhook
            Method: POST
      Policies:
        - SNSPublishMessagePolicy:
            TopicName: !Ref notifyTopic
      Environment:
        Variables:
          SECRET: !Ref Secret
          GH_TOKEN: !Ref GHToken
  notifyTopic:
    Type: AWS::SNS::Topic
    Properties:
      DisplayName: !Sub "${AWS::StackName}-notifyGitHubBranchProtection"
      TopicName: !Sub "${AWS::StackName}-notifyGitHubBranchProtection"
      Subscription:
        - Endpoint: !Ref SubscriptionEmail
          Protocol: email
Outputs:
  processWebhookApiEndpoint:
    Description: API Gateway endpoint URL for Prod stage for processWebhook function
    Value: !Sub https://${processWebhookApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/processWebhook
